In [1]:
import numpy as np


In [2]:
a=np.array([3,4,5])
a.itemsize

4

In [3]:
a=zeros.array((3,4))

NameError: name 'zeros' is not defined

In [5]:
a=np.zeros((3,4))

In [6]:
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [8]:
np.arange(0,6,2)

array([0, 2, 4])

In [9]:
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
a=np.array([2,3],[4,6],[6,7])
np.sqrt(a)

ValueError: only 2 non-keyword arguments accepted

In [11]:
a=np.array([2,3],[4,6],[6,7])


ValueError: only 2 non-keyword arguments accepted

In [13]:
a=np.array([[2,3],[4,6],[6,7]])


In [14]:
np.sqrt(a)

array([[1.41421356, 1.73205081],
       [2.        , 2.44948974],
       [2.44948974, 2.64575131]])